# Generated by Django 5.2.12 on 2026-03-11 14:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('candidates', '0001_initial'),
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage', models.CharField(choices=[('applied', 'Applied'), ('screening', 'Screening'), ('initial_interview', 'Initial Interview'), ('exam', 'Exam'), ('departmental_interview', 'Departmental Interview'), ('final_interview', 'Final Interview'), ('job_offer', 'Job Offer'), ('hired', 'Hired'), ('rejected', 'Rejected')], default='applied', max_length=32)),
                ('source', models.CharField(blank=True, max_length=64)),
                ('rating', models.PositiveSmallIntegerField(default=0)),
                ('recruiter_name', models.CharField(blank=True, max_length=255)),
                ('notes', models.TextField(blank=True)),
                ('resume_file', models.FileField(blank=True, null=True, upload_to='resumes/')),
                ('exam_result_file', models.FileField(blank=True, null=True, upload_to='exam-results/')),
                ('applied_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='candidates.candidate')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='jobs.job')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
    ]
