# Generated by Django 5.2.12 on 2026-03-13 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('dept', models.CharField(blank=True, default='', max_length=100)),
                ('location', models.CharField(choices=[('Bluewater Maribago', 'Bluewater Maribago'), ('Bluewater Sumilon', 'Bluewater Sumilon'), ('Bluewater Panglao', 'Bluewater Panglao'), ('Almont Inland', 'Almont Inland'), ('Almont Beach Resort', 'Almont Beach Resort'), ('Almont City Hotel', 'Almont City Hotel'), ('Amuma Spa', 'Amuma Spa'), ('Blue Bubble', 'Blue Bubble')], max_length=100)),
                ('type', models.CharField(choices=[('Full-time', 'Full-time'), ('Part-time', 'Part-time'), ('Contract', 'Contract'), ('Internship', 'Internship')], max_length=50)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Closed', 'Closed')], default='Active', max_length=20)),
                ('posted', models.CharField(max_length=50)),
                ('closed', models.CharField(blank=True, max_length=50, null=True)),
                ('description', models.TextField(blank=True, default='')),
                ('qualifications', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'jobs',
                'ordering': ['-id'],
            },
        ),
    ]
