# Generated by Django 5.2.12 on 2026-03-13 16:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_jobapplication'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobapplication',
            name='source',
            field=models.CharField(choices=[('Website', 'Website'), ('LinkedIn', 'LinkedIn'), ('Indeed', 'Indeed'), ('Referral', 'Referral'), ('Endorsed', 'Endorsed'), ('Other', 'Other')], default='Website', max_length=30),
        ),
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage', models.CharField(choices=[('Applied', 'Applied'), ('Screening', 'Screening'), ('Initial Interview', 'Initial Interview'), ('Exam', 'Exam'), ('Departmental Interview', 'Departmental Interview'), ('Final Interview', 'Final Interview'), ('Job Offer', 'Job Offer'), ('Hired', 'Hired'), ('Rejected', 'Rejected')], default='Applied', max_length=50)),
                ('rating', models.IntegerField(default=0)),
                ('notes', models.TextField(blank=True, default='')),
                ('exam_result', models.FileField(blank=True, null=True, upload_to='exam-results/')),
                ('endorsed_from', models.CharField(blank=True, max_length=200, null=True)),
                ('is_pooled', models.BooleanField(default=False)),
                ('pooled_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('application', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='candidate', to='jobs.jobapplication')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidates', to='jobs.job')),
                ('recruiter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_candidates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'candidates',
                'ordering': ['-created_at'],
            },
        ),
    ]
