# Generated by Django 5.2.12 on 2026-03-13 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_candidate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='endorsed_from',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='job',
            name='qualifications',
            field=models.TextField(blank=True, default=''),
        ),
    ]
