# Generated by Django 5.2.12 on 2026-03-16 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0004_fix_null_text_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='job',
            name='qualifications',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='jobapplication',
            name='agreement',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='jobapplication',
            name='source',
            field=models.CharField(choices=[('Website', 'Website'), ('LinkedIn', 'LinkedIn'), ('Indeed', 'Indeed'), ('Referral', 'Referral'), ('Endorsed', 'Endorsed'), ('Other', 'Other')], max_length=30),
        ),
    ]
