# Generated by Django 5.2.12 on 2026-03-12 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(blank=True, choices=[('hr_manager', 'HR Manager'), ('talent_acquisition_specialist', 'Talent Acquisition Specialist'), ('talent_acquisition_manager', 'Talent Acquisition Manager')], default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
