# Generated by Django 5.2.12 on 2026-03-16 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_user_role_alter_user_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('hr_manager', 'HR Manager'), ('talent_acquisition_specialist', 'Talent Acquisition Specialist'), ('talent_acquisition_manager', 'Talent Acquisition Manager')], max_length=50),
        ),
    ]
